-- Crear tabla "comments"
CREATE TABLE public.comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    user_name text NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad para los comentarios

-- 1. Cualquier persona puede leer los comentarios de un proyecto
CREATE POLICY "Permitir lectura publica de comentarios" 
ON public.comments FOR SELECT 
USING (true);

-- 2. Solo los usuarios autenticados pueden insertar comentarios
-- y su `user_id` debe coincidir con su ID de autenticación.
CREATE POLICY "Usuarios autenticados pueden comentar" 
ON public.comments FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 3. (Opcional) Usuarios autenticados pueden borrar sus propios comentarios
CREATE POLICY "Usuarios pueden borrar sus propios comentarios"
ON public.comments FOR DELETE
USING (auth.uid() = user_id);
