-- Crear tabla "projects"
CREATE TABLE public.projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    excerpt text,
    description text,
    tags text[],
    image_urls text[], -- Array para guardar 1 o 100 fotos (las que quieras)
    download_provider text DEFAULT 'both'::text, -- Opciones: 'both', 'drive', 'mediafire'
    drive_url text,
    mediafire_url text,
    link text
);

-- Configurar RLS (Row Level Security) para que cualquiera pueda leer, 
-- pero solo tú (o un admin) pueda insertar/actualizar desde la interfaz de Supabase.
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura publica de proyectos" 
ON public.projects FOR SELECT 
USING (true);

-- (Opcional) Si quieres añadir un proyecto de prueba desde SQL:
/*
INSERT INTO public.projects (title, excerpt, description, tags, image_urls, download_provider, drive_url, mediafire_url)
VALUES (
    'Proyecto de Ejemplo',
    'Un breve resumen de mi proyecto para la tarjeta.',
    'Aquí va la descripción súper detallada del proyecto que aparecerá cuando la gente le de a Ver Más. Puedes escribir varios párrafos.',
    ARRAY['Juego', 'Unity', '3D'],
    ARRAY['https://ejemplo.com/foto1.png', 'https://ejemplo.com/foto2.png'],
    'both',
    'https://drive.google.com/file/d/ejemplo',
    'https://mediafire.com/file/ejemplo'
);
*/
